# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/philipp/Desktop/Compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/philipp/Desktop/Compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/philipp/Desktop/Compiler/CMakeFiles /home/philipp/Desktop/Compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/philipp/Desktop/Compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Compiler

# Build rule for target.
Compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Compiler
.PHONY : Compiler

# fast build rule for target.
Compiler/fast:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/build
.PHONY : Compiler/fast

Source/Assembler/Assembler.o: Source/Assembler/Assembler.cpp.o

.PHONY : Source/Assembler/Assembler.o

# target to build an object file
Source/Assembler/Assembler.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Assembler/Assembler.cpp.o
.PHONY : Source/Assembler/Assembler.cpp.o

Source/Assembler/Assembler.i: Source/Assembler/Assembler.cpp.i

.PHONY : Source/Assembler/Assembler.i

# target to preprocess a source file
Source/Assembler/Assembler.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Assembler/Assembler.cpp.i
.PHONY : Source/Assembler/Assembler.cpp.i

Source/Assembler/Assembler.s: Source/Assembler/Assembler.cpp.s

.PHONY : Source/Assembler/Assembler.s

# target to generate assembly for a file
Source/Assembler/Assembler.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Assembler/Assembler.cpp.s
.PHONY : Source/Assembler/Assembler.cpp.s

Source/Assembler/Labels.o: Source/Assembler/Labels.cpp.o

.PHONY : Source/Assembler/Labels.o

# target to build an object file
Source/Assembler/Labels.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Assembler/Labels.cpp.o
.PHONY : Source/Assembler/Labels.cpp.o

Source/Assembler/Labels.i: Source/Assembler/Labels.cpp.i

.PHONY : Source/Assembler/Labels.i

# target to preprocess a source file
Source/Assembler/Labels.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Assembler/Labels.cpp.i
.PHONY : Source/Assembler/Labels.cpp.i

Source/Assembler/Labels.s: Source/Assembler/Labels.cpp.s

.PHONY : Source/Assembler/Labels.s

# target to generate assembly for a file
Source/Assembler/Labels.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Assembler/Labels.cpp.s
.PHONY : Source/Assembler/Labels.cpp.s

Source/Common/Char_buffers.o: Source/Common/Char_buffers.cpp.o

.PHONY : Source/Common/Char_buffers.o

# target to build an object file
Source/Common/Char_buffers.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Char_buffers.cpp.o
.PHONY : Source/Common/Char_buffers.cpp.o

Source/Common/Char_buffers.i: Source/Common/Char_buffers.cpp.i

.PHONY : Source/Common/Char_buffers.i

# target to preprocess a source file
Source/Common/Char_buffers.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Char_buffers.cpp.i
.PHONY : Source/Common/Char_buffers.cpp.i

Source/Common/Char_buffers.s: Source/Common/Char_buffers.cpp.s

.PHONY : Source/Common/Char_buffers.s

# target to generate assembly for a file
Source/Common/Char_buffers.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Char_buffers.cpp.s
.PHONY : Source/Common/Char_buffers.cpp.s

Source/Common/Common.o: Source/Common/Common.cpp.o

.PHONY : Source/Common/Common.o

# target to build an object file
Source/Common/Common.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Common.cpp.o
.PHONY : Source/Common/Common.cpp.o

Source/Common/Common.i: Source/Common/Common.cpp.i

.PHONY : Source/Common/Common.i

# target to preprocess a source file
Source/Common/Common.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Common.cpp.i
.PHONY : Source/Common/Common.cpp.i

Source/Common/Common.s: Source/Common/Common.cpp.s

.PHONY : Source/Common/Common.s

# target to generate assembly for a file
Source/Common/Common.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Common.cpp.s
.PHONY : Source/Common/Common.cpp.s

Source/Common/Trees.o: Source/Common/Trees.cpp.o

.PHONY : Source/Common/Trees.o

# target to build an object file
Source/Common/Trees.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Trees.cpp.o
.PHONY : Source/Common/Trees.cpp.o

Source/Common/Trees.i: Source/Common/Trees.cpp.i

.PHONY : Source/Common/Trees.i

# target to preprocess a source file
Source/Common/Trees.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Trees.cpp.i
.PHONY : Source/Common/Trees.cpp.i

Source/Common/Trees.s: Source/Common/Trees.cpp.s

.PHONY : Source/Common/Trees.s

# target to generate assembly for a file
Source/Common/Trees.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Common/Trees.cpp.s
.PHONY : Source/Common/Trees.cpp.s

Source/Compiler/Compiler_unit_test.o: Source/Compiler/Compiler_unit_test.cpp.o

.PHONY : Source/Compiler/Compiler_unit_test.o

# target to build an object file
Source/Compiler/Compiler_unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Compiler_unit_test.cpp.o
.PHONY : Source/Compiler/Compiler_unit_test.cpp.o

Source/Compiler/Compiler_unit_test.i: Source/Compiler/Compiler_unit_test.cpp.i

.PHONY : Source/Compiler/Compiler_unit_test.i

# target to preprocess a source file
Source/Compiler/Compiler_unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Compiler_unit_test.cpp.i
.PHONY : Source/Compiler/Compiler_unit_test.cpp.i

Source/Compiler/Compiler_unit_test.s: Source/Compiler/Compiler_unit_test.cpp.s

.PHONY : Source/Compiler/Compiler_unit_test.s

# target to generate assembly for a file
Source/Compiler/Compiler_unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Compiler_unit_test.cpp.s
.PHONY : Source/Compiler/Compiler_unit_test.cpp.s

Source/Compiler/Lexical_analyzer.o: Source/Compiler/Lexical_analyzer.cpp.o

.PHONY : Source/Compiler/Lexical_analyzer.o

# target to build an object file
Source/Compiler/Lexical_analyzer.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Lexical_analyzer.cpp.o
.PHONY : Source/Compiler/Lexical_analyzer.cpp.o

Source/Compiler/Lexical_analyzer.i: Source/Compiler/Lexical_analyzer.cpp.i

.PHONY : Source/Compiler/Lexical_analyzer.i

# target to preprocess a source file
Source/Compiler/Lexical_analyzer.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Lexical_analyzer.cpp.i
.PHONY : Source/Compiler/Lexical_analyzer.cpp.i

Source/Compiler/Lexical_analyzer.s: Source/Compiler/Lexical_analyzer.cpp.s

.PHONY : Source/Compiler/Lexical_analyzer.s

# target to generate assembly for a file
Source/Compiler/Lexical_analyzer.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Lexical_analyzer.cpp.s
.PHONY : Source/Compiler/Lexical_analyzer.cpp.s

Source/Compiler/Recursive_descent.o: Source/Compiler/Recursive_descent.cpp.o

.PHONY : Source/Compiler/Recursive_descent.o

# target to build an object file
Source/Compiler/Recursive_descent.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Recursive_descent.cpp.o
.PHONY : Source/Compiler/Recursive_descent.cpp.o

Source/Compiler/Recursive_descent.i: Source/Compiler/Recursive_descent.cpp.i

.PHONY : Source/Compiler/Recursive_descent.i

# target to preprocess a source file
Source/Compiler/Recursive_descent.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Recursive_descent.cpp.i
.PHONY : Source/Compiler/Recursive_descent.cpp.i

Source/Compiler/Recursive_descent.s: Source/Compiler/Recursive_descent.cpp.s

.PHONY : Source/Compiler/Recursive_descent.s

# target to generate assembly for a file
Source/Compiler/Recursive_descent.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Recursive_descent.cpp.s
.PHONY : Source/Compiler/Recursive_descent.cpp.s

Source/Compiler/Semantical_analyzer.o: Source/Compiler/Semantical_analyzer.cpp.o

.PHONY : Source/Compiler/Semantical_analyzer.o

# target to build an object file
Source/Compiler/Semantical_analyzer.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Semantical_analyzer.cpp.o
.PHONY : Source/Compiler/Semantical_analyzer.cpp.o

Source/Compiler/Semantical_analyzer.i: Source/Compiler/Semantical_analyzer.cpp.i

.PHONY : Source/Compiler/Semantical_analyzer.i

# target to preprocess a source file
Source/Compiler/Semantical_analyzer.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Semantical_analyzer.cpp.i
.PHONY : Source/Compiler/Semantical_analyzer.cpp.i

Source/Compiler/Semantical_analyzer.s: Source/Compiler/Semantical_analyzer.cpp.s

.PHONY : Source/Compiler/Semantical_analyzer.s

# target to generate assembly for a file
Source/Compiler/Semantical_analyzer.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Semantical_analyzer.cpp.s
.PHONY : Source/Compiler/Semantical_analyzer.cpp.s

Source/Compiler/Syntax_declaration.o: Source/Compiler/Syntax_declaration.cpp.o

.PHONY : Source/Compiler/Syntax_declaration.o

# target to build an object file
Source/Compiler/Syntax_declaration.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Syntax_declaration.cpp.o
.PHONY : Source/Compiler/Syntax_declaration.cpp.o

Source/Compiler/Syntax_declaration.i: Source/Compiler/Syntax_declaration.cpp.i

.PHONY : Source/Compiler/Syntax_declaration.i

# target to preprocess a source file
Source/Compiler/Syntax_declaration.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Syntax_declaration.cpp.i
.PHONY : Source/Compiler/Syntax_declaration.cpp.i

Source/Compiler/Syntax_declaration.s: Source/Compiler/Syntax_declaration.cpp.s

.PHONY : Source/Compiler/Syntax_declaration.s

# target to generate assembly for a file
Source/Compiler/Syntax_declaration.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Compiler/Syntax_declaration.cpp.s
.PHONY : Source/Compiler/Syntax_declaration.cpp.s

Source/Lists/Language_keywords_and_types_enum.o: Source/Lists/Language_keywords_and_types_enum.cpp.o

.PHONY : Source/Lists/Language_keywords_and_types_enum.o

# target to build an object file
Source/Lists/Language_keywords_and_types_enum.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Lists/Language_keywords_and_types_enum.cpp.o
.PHONY : Source/Lists/Language_keywords_and_types_enum.cpp.o

Source/Lists/Language_keywords_and_types_enum.i: Source/Lists/Language_keywords_and_types_enum.cpp.i

.PHONY : Source/Lists/Language_keywords_and_types_enum.i

# target to preprocess a source file
Source/Lists/Language_keywords_and_types_enum.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Lists/Language_keywords_and_types_enum.cpp.i
.PHONY : Source/Lists/Language_keywords_and_types_enum.cpp.i

Source/Lists/Language_keywords_and_types_enum.s: Source/Lists/Language_keywords_and_types_enum.cpp.s

.PHONY : Source/Lists/Language_keywords_and_types_enum.s

# target to generate assembly for a file
Source/Lists/Language_keywords_and_types_enum.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Lists/Language_keywords_and_types_enum.cpp.s
.PHONY : Source/Lists/Language_keywords_and_types_enum.cpp.s

Source/Processor/Processor.o: Source/Processor/Processor.cpp.o

.PHONY : Source/Processor/Processor.o

# target to build an object file
Source/Processor/Processor.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Processor/Processor.cpp.o
.PHONY : Source/Processor/Processor.cpp.o

Source/Processor/Processor.i: Source/Processor/Processor.cpp.i

.PHONY : Source/Processor/Processor.i

# target to preprocess a source file
Source/Processor/Processor.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Processor/Processor.cpp.i
.PHONY : Source/Processor/Processor.cpp.i

Source/Processor/Processor.s: Source/Processor/Processor.cpp.s

.PHONY : Source/Processor/Processor.s

# target to generate assembly for a file
Source/Processor/Processor.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Processor/Processor.cpp.s
.PHONY : Source/Processor/Processor.cpp.s

Source/Processor/Stack.o: Source/Processor/Stack.cpp.o

.PHONY : Source/Processor/Stack.o

# target to build an object file
Source/Processor/Stack.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Processor/Stack.cpp.o
.PHONY : Source/Processor/Stack.cpp.o

Source/Processor/Stack.i: Source/Processor/Stack.cpp.i

.PHONY : Source/Processor/Stack.i

# target to preprocess a source file
Source/Processor/Stack.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Processor/Stack.cpp.i
.PHONY : Source/Processor/Stack.cpp.i

Source/Processor/Stack.s: Source/Processor/Stack.cpp.s

.PHONY : Source/Processor/Stack.s

# target to generate assembly for a file
Source/Processor/Stack.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/Processor/Stack.cpp.s
.PHONY : Source/Processor/Stack.cpp.s

Source/main.o: Source/main.cpp.o

.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i

.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s

.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Compiler"
	@echo "... Source/Assembler/Assembler.o"
	@echo "... Source/Assembler/Assembler.i"
	@echo "... Source/Assembler/Assembler.s"
	@echo "... Source/Assembler/Labels.o"
	@echo "... Source/Assembler/Labels.i"
	@echo "... Source/Assembler/Labels.s"
	@echo "... Source/Common/Char_buffers.o"
	@echo "... Source/Common/Char_buffers.i"
	@echo "... Source/Common/Char_buffers.s"
	@echo "... Source/Common/Common.o"
	@echo "... Source/Common/Common.i"
	@echo "... Source/Common/Common.s"
	@echo "... Source/Common/Trees.o"
	@echo "... Source/Common/Trees.i"
	@echo "... Source/Common/Trees.s"
	@echo "... Source/Compiler/Compiler_unit_test.o"
	@echo "... Source/Compiler/Compiler_unit_test.i"
	@echo "... Source/Compiler/Compiler_unit_test.s"
	@echo "... Source/Compiler/Lexical_analyzer.o"
	@echo "... Source/Compiler/Lexical_analyzer.i"
	@echo "... Source/Compiler/Lexical_analyzer.s"
	@echo "... Source/Compiler/Recursive_descent.o"
	@echo "... Source/Compiler/Recursive_descent.i"
	@echo "... Source/Compiler/Recursive_descent.s"
	@echo "... Source/Compiler/Semantical_analyzer.o"
	@echo "... Source/Compiler/Semantical_analyzer.i"
	@echo "... Source/Compiler/Semantical_analyzer.s"
	@echo "... Source/Compiler/Syntax_declaration.o"
	@echo "... Source/Compiler/Syntax_declaration.i"
	@echo "... Source/Compiler/Syntax_declaration.s"
	@echo "... Source/Lists/Language_keywords_and_types_enum.o"
	@echo "... Source/Lists/Language_keywords_and_types_enum.i"
	@echo "... Source/Lists/Language_keywords_and_types_enum.s"
	@echo "... Source/Processor/Processor.o"
	@echo "... Source/Processor/Processor.i"
	@echo "... Source/Processor/Processor.s"
	@echo "... Source/Processor/Stack.o"
	@echo "... Source/Processor/Stack.i"
	@echo "... Source/Processor/Stack.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

